name: Codespaces Setup Check

on:
  pull_request:
    paths:
      - ".devcontainer/**"
  workflow_dispatch:

jobs:
  validate-devcontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate devcontainer.json
        run: |
          if ! jq empty .devcontainer/devcontainer.json; then
            echo "devcontainer.json is not valid JSON"
            exit 1
          fi
          echo "devcontainer.json is valid"
